name: "Github action"
on:
  push:
    branches:
      - main
  pull_request:
permissions:
      id-token: write # This is required for aws oidc connection
      contents: read # This is required for actions/checkout
      pull-requests: write # This is required for gh bot to comment PR
env:
  TF_LOG: INFO
  AWS_REGION: "us-east-1" #Change to reflect your Region
jobs:
  docker-creation:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - name: Git checkout
        uses: actions/checkout@v3    

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
            role-to-assume: arn:aws:iam::644107485976:role/github_actions_role #change to reflect your IAM role’s ARN
            role-session-name: GitHub_to_AWS_via_FederatedOIDC
            aws-region: ${{ env.AWS_REGION }}
  
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1.7.0
        with:
          mask-password: 'true'
  
      - name: Build and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: nodeapp
          IMAGE_TAG: latest
        run: |
          cat src/index.ts
          echo $ECR_REGISTRY  && echo $ECR_REPOSITORY && echo $IMAGE_TAG
          docker build -t $ECR_REPOSITORY .
          docker tag $ECR_REPOSITORY $ECR_REGISTRY/$ECR_REPOSITORY
          docker push $ECR_REGISTRY/$ECR_REPOSITORY
  deploy:
    runs-on: ubuntu-latest
    permissions: write-all
    needs: [docker-creation]
    outputs:
      NEWEC2PUBLICIP: ${{ steps.set-ip.outputs.NEWEC2PUBLICIP }}
      PRIVATEKEY: ${{ steps.privatekey.outputs.result }}
      PRIVKEY: ${{ steps.set-ip2.outputs.PRIVKEY }}
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::644107485976:role/github_actions_role #change to reflect your IAM role’s ARN
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2


      - name: Terraform fmt
        id: fmt
        run: terraform fmt
        continue-on-error: true

      - name: Terraform Init
        id: init
        env:
          AWS_BUCKET_NAME: "tf-state-manu16082023"
          AWS_BUCKET_KEY_NAME: "remote-state"
        run: terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=${{env.AWS_BUCKET_KEY_NAME}}" -backend-config="region=${{env.AWS_REGION}}"

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        if: github.event_name == 'pull_request'
        continue-on-error: true

      - uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
            <details><summary>Validation Output</summary>

            \`\`\`\n
            ${{ steps.validate.outputs.stdout }}
            \`\`\`

            </details>

            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`

            </details>

            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false

      - name: Terraform Output
        run: |
          terraform-bin output -json  | jq  -r '.ec2_private_key.value' > ec2_private.pem
          cat ec2_private.pem

      - name: Set privatekey to var
        uses: actions/github-script@v4
        id: privatekey
        with:
          script: |
            const fs = require('fs');
            return fs.readFileSync('ec2_private.pem','utf8').toString();
          result-encoding: string

      - name: Set Output
        id: set-ip
        run: |
          echo "NEWEC2PUBLICIP=$(terraform-bin output  -json | jq  -r '.new_public_ip.value')" >> $GITHUB_OUTPUT

      - name: Set Output2
        id: set-ip2
        run: |
          delimiter="$(openssl rand -hex 8)"
          echo "PRIVKEY<<${delimiter}" >> "${GITHUB_OUTPUT}"
          echo "Some\nMultiline\nOutput" >> "${GITHUB_OUTPUT}"
          echo "${delimiter}" >> "${GITHUB_OUTPUT}"    

  pull-docker-image:
    runs-on: ubuntu-latest
    needs: [deploy]
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - name: Use the value
        id: use_value
        run: |
          echo "I'm running on ${{ needs.deploy.outputs.NEWEC2PUBLICIP }}" 
          echo "${{ needs.deploy.outputs.PRIVATEKEY }}" > ec2_private.pem
          echo "${{ needs.deploy.outputs.PRIVKEY }}"

      - name: SSH Action
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ needs.deploy.outputs.NEWEC2PUBLICIP }}
          username: "ubuntu"
          key_path:  ec2_private.pem
          port: "22"
          script: |
            whoami
            (docker stop app_deploy || true)
            docker run --pull=always --rm --name app_deploy -d -p 3000:3000 644107485976.dkr.ecr.us-east-1.amazonaws.com/nodeapp:latest